# Site settings
title: Digital tools
subtitle: used in communities
email: 
description: > # this means to ignore newlines until "baseurl:"
  Online tools available for community management and activities
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dt.haldjas.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

# Analytics
google_analytics_id: UA-59364668-2
keywords: "tools, digital tools, community tools"

# Content types
collections:
  tools:
    output: true

#Default settings by content types
defaults: 
  - 
    scope:
      path: ""
      type: "tools"
    values:
      layout: default

